In [95]:
import torch
import numpy as np

In [72]:
# uninitialized matrix
# contains whatever vals in allocated memory at the time
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38],
        [9.6429e-39, 9.2755e-39, 9.7346e-39],
        [1.0745e-38, 1.0102e-38, 9.9184e-39]])


In [73]:
# randomly initialized matrix
x = torch.randn(5, 3)
print(x)

tensor([[ 0.5948, -0.7592, -0.7659],
        [-1.5243,  0.9289, -0.7383],
        [ 0.4419, -0.5221, -0.8800],
        [ 0.4103,  0.7859,  0.0930],
        [-1.3403, -0.7935,  0.6092]])


In [78]:
# add dtype
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [80]:
# tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [83]:
# tensor based on existing tensor
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7431,  0.3100, -0.5082],
        [ 0.6791, -1.1422,  0.6354],
        [ 0.4991,  0.2810,  0.8325],
        [ 0.5438,  0.7514, -0.0562],
        [ 0.8448,  0.1931,  0.3077]])
torch.Size([5, 3])


In [88]:
# addition
y = torch.rand(5, 3)
print(x + y)
# providing output as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
# inplace
y.add_(x)
print(y)

tensor([[-0.0960,  1.2971,  0.3986],
        [ 1.0292, -0.2455,  0.8642],
        [ 1.0203,  0.5797,  1.5563],
        [ 1.4379,  1.6869,  0.5911],
        [ 1.1041,  0.4989,  0.8936]])
tensor([[-0.0960,  1.2971,  0.3986],
        [ 1.0292, -0.2455,  0.8642],
        [ 1.0203,  0.5797,  1.5563],
        [ 1.4379,  1.6869,  0.5911],
        [ 1.1041,  0.4989,  0.8936]])
tensor([[-0.0960,  1.2971,  0.3986],
        [ 1.0292, -0.2455,  0.8642],
        [ 1.0203,  0.5797,  1.5563],
        [ 1.4379,  1.6869,  0.5911],
        [ 1.1041,  0.4989,  0.8936]])


In [96]:
# slicing
print(x)
print(x[:, 1])

# resizing using view()
x = torch.rand(4,4)
y = x.view(-1)
z = x.view(-1, 8)
print(x, y, z)
print(x.size(), y.size(), z.size())

# converting to numpy array
print(x.numpy())

# numpy to tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

tensor([[0.6473, 0.1108, 0.5802, 0.1133],
        [0.3901, 0.3106, 0.1916, 0.9124],
        [0.3098, 0.9344, 0.0230, 0.5549],
        [0.3446, 0.6507, 0.3117, 0.5594]])
tensor([0.1108, 0.3106, 0.9344, 0.6507])
tensor([[0.9802, 0.8569, 0.0237, 0.0141],
        [0.7832, 0.3197, 0.5662, 0.1988],
        [0.1545, 0.6469, 0.9830, 0.6842],
        [0.9900, 0.2885, 0.5831, 0.4760]]) tensor([0.9802, 0.8569, 0.0237, 0.0141, 0.7832, 0.3197, 0.5662, 0.1988, 0.1545,
        0.6469, 0.9830, 0.6842, 0.9900, 0.2885, 0.5831, 0.4760]) tensor([[0.9802, 0.8569, 0.0237, 0.0141, 0.7832, 0.3197, 0.5662, 0.1988],
        [0.1545, 0.6469, 0.9830, 0.6842, 0.9900, 0.2885, 0.5831, 0.4760]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
[[0.98016816 0.8569128  0.02372855 0.01408398]
 [0.7831647  0.31974298 0.5661779  0.19877106]
 [0.15454817 0.6469281  0.9829619  0.6841901 ]
 [0.9900485  0.28846335 0.5830608  0.47603035]]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
